name: Docker Image CI

on:
  push:http://webdav@192.168.1.118:8080/
    branches: [ "kingznqueenzspa@icloud.com" ]
  pull_request:svvaladez11
    branches: [ "svgarza" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
